### ISSUE TITLE
Unresponsive, slow, stuck on loading

### ISSUE THREAD

**Issue by Zohvek** [terrajobst/themesof.net#13]
There seems to be an issue with the website that is currently live. Its slow to render the menu bar, and footer, then will seemingly sit on "loading..." as the only content served in the body region.. indefinitely.

**Comment by terrajobst** [comment]
It seems we have run into the case where the way the site pulls from GitHub caused the abuse detection algorithm to fail the requests. It's not fixed; I only worked around the issue causing the site to refresh much slower but at least it should display data.

**Comment by terrajobst** [comment]
It seems we got this under control now.
