### ISSUE TITLE
Filtering by repository?

### ISSUE THREAD

**Issue by Pilchie** [terrajobst/themesof.net#6]
Within runtime, the Team: labels work pretty well, but I'd love to be able to filter to all the issues in the aspnetcore repo for example...

**Comment by terrajobst** [comment]
Do you need a drop down or is this sufficient?

https://themesof.net/?q=aspnetcore#%20is:open%20kinds:teu

Basically, all the displayed information (org/repo#id, assignee, title, labels) can be full text searched via the text box.

**Comment by Pilchie** [comment]
Doh, now that you mention it, I remember that I did find that once before, but then forgot it.  It's probably fine.
